version: "3.9"

services:
  tf_serving:
    container_name: iana
    image: tensorflow/serving:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./src/models/saved_model:/tfserving
    networks:
      - libra-translate-network
    entrypoint: ["/usr/bin/tf_serving_entrypoint.sh"]
    command: ["--model_name=iana", "--model_base_path=/tfserving/iana"]

networks:
  libra-translate-network:
    external: true
